# -*- coding: utf-8 -*-
"""Main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gfxKu1K9Ft7-kA4AqN4N4VSVdFaVbGR
"""

from fastapi import FastAPI, Query
from fastapi.middleware.cors import CORSMiddleware
from datetime import datetime, timedelta
import ee
import json
import os

app = FastAPI(title="AquaFertile GEE Engine")

# Izinkan request dari frontend (CORS)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Inisialisasi GEE Service Account
KEY_FILE = os.getenv("GEE_KEY_FILE", "credentials_gee.json")
with open(KEY_FILE) as f:
    key_data = json.load(f)

credentials = ee.ServiceAccountCredentials(key_data["client_email"], KEY_FILE)
ee.Initialize(credentials, project="aquafertile-marine")

AOI = ee.Geometry.Rectangle([114.2, -8.9, 114.8, -8.1])

@app.get("/api/health")
def health_check():
    return {"status": "ok", "project": "aquafertile-marine"}

@app.get("/api/tiles")
def get_dynamic_tiles(date: str = Query(..., description="Format: YYYY-MM-DD")):
    try:
        # Tentukan rentang waktu 7 hari ke belakang dari tanggal yang dipilih agar citra tidak kosong
        target_date = datetime.strptime(date, "%Y-%m-%d")
        start_date = (target_date - timedelta(days=7)).strftime("%Y-%m-%d")
        end_date = (target_date + timedelta(days=1)).strftime("%Y-%m-%d")

        # 1. Klorofil-a (MODIS Aqua)
        chla_col = (
            ee.ImageCollection("NASA/OCEANDATA/MODIS-Aqua/L3SMI")
            .select("chlor_a")
            .filterDate(start_date, end_date)
            .sort("system:time_start", False)
        )
        # Fallback ke data terbaru jika pada rentang tanggal tersebut tertutup awan total
        chla = ee.Algorithms.If(
            chla_col.size().gt(0),
            chla_col.mean().clip(AOI),
            ee.ImageCollection("NASA/OCEANDATA/MODIS-Aqua/L3SMI").select("chlor_a").sort("system:time_start", False).limit(5).mean().clip(AOI)
        )
        chla_img = ee.Image(chla)

        # 2. SST (NOAA OISST)
        sst_col = (
            ee.ImageCollection("NOAA/CDR/OISST/V2_1")
            .select("sst")
            .filterDate(start_date, end_date)
            .sort("system:time_start", False)
        )
        sst = ee.Algorithms.If(
            sst_col.size().gt(0),
            sst_col.mean().multiply(0.01).clip(AOI),
            ee.ImageCollection("NOAA/CDR/OISST/V2_1").select("sst").sort("system:time_start", False).limit(5).mean().multiply(0.01).clip(AOI)
        )
        sst_img = ee.Image(sst)

        # 3. Batimetri & Masking Laut
        depth = ee.Image("NOAA/NGDC/ETOPO1").select("bedrock").clip(AOI)
        sea_mask = depth.lt(0)

        # 4. MCE Scoring
        s_chla = chla_img.expression("b() >= 3.0 ? 4 : (b() >= 1.0 ? 3 : 2)")
        s_sst = sst_img.expression("b() <= 27.5 ? 4 : (b() <= 29.0 ? 3 : 2)")
        s_depth = depth.abs().expression("b() <= 50 ? 4 : (b() <= 150 ? 3 : 2)")

        mce_score = (
            s_chla.multiply(0.50)
            .add(s_sst.multiply(0.25))
            .add(s_depth.multiply(0.25))
            .updateMask(sea_mask)
        )

        vis_mce = {
            "min": 2.0,
            "max": 4.0,
            "palette": ["#06b6d4", "#10b981", "#f59e0b", "#ef4444"]
        }

        map_id = ee.data.getMapId({"image": mce_score.visualize(**vis_mce)})
        tile_url = map_id["tile_fetcher"].url_format

        return {
            "success": True,
            "date": date,
            "tile_url": tile_url
        }

    except Exception as e:
        return {"success": False, "error": str(e)}

